version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - sudo apt-get install -y nginx
      - npm install
  build:
    commands:
      - echo Building Next.js application...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: .
